# Generated by Django 4.1.7 on 2023-12-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_invoice_created_at_invoice_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
    ]
