# Generated by Django 4.1.7 on 2024-01-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_invoiceitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
