# Generated by Django 4.1.7 on 2024-01-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_invoiceitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='debit_amount',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='loading_amount',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='debit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='loading_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
