# Generated by Django 4.1.7 on 2024-01-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_invoiceitem_debit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
